### PR TITLE
Added AF_XDP support in XDP code.

### PR DESCRIPTION
**Pull request by zzxgzgz**
This PR achieves the following:

- Added xsks map for af_xdp; redirect packets to userspace via xsks map when xdp couldn't find endpoint in ebpf map.

### CODE REVIEW

**Comment by xieus** [comment]
Please review this PR @lfu-ps and @w-yue asap.

**Review by w-yue — CHANGES_REQUESTED** [review]
It is possible to move this logic to earlier part? In general, it's better not to "change" the semantic of "XDP_DROP".

**Comment by w-yue** [comment]
There are more than 10 places returning “XDP_DROP” in this file, you should move this logic to the specific place right before can’t find the endpoint in map and “return XDP_DROP” in that function. You don’t want to forward garbage packets to use space vis AF_XDP.

From: Rio Zhu ***@***.***>
Date: Tuesday, January 24, 2023 at 9:01 AM
To: futurewei-cloud/arion-dp ***@***.***>
Cc: Wei Yue ***@***.***>, Mention ***@***.***>
Subject: Re: [futurewei-cloud/arion-dp] Added AF_XDP support in XDP code. (PR #8)

It is possible to move this logic to earlier part? In general, it's better not to "change" the semantic of "XDP_DROP".

Which earlier part would you suggest? I think it is good at where it is now, as action == XDP_DROP triggers when the process_$(some_layter) fails(e.g. when an endpoint cannot be found in the eBPF map).

**Comment by zzxgzgz** [comment]
> 

Makes sense. Please check my commit [e11568b](https://github.com/futurewei-cloud/arion-dp/pull/8/commits/e11568b293d2957c4a58c06f3eab78dd7f609e79), where I created a `const int EP_NOT_FOUND` for this specific scenario.

Thank you.

**Review by w-yue — CHANGES_REQUESTED** [review]
Here EP_NOT_FOUND is defined the same as XDP_REDIRECT which is misleading.

I would suggest to put your logic as a function and call your function in these two places where you put "return EP_NOT_FOUND" instead.

**Comment by zzxgzgz** [comment]
> Here EP_NOT_FOUND is defined the same as XDP_REDIRECT which is misleading.
> 
> I would suggest to put your logic as a function and call your function in these two places where you put "return EP_NOT_FOUND" instead.

If I'm not mistaken, `EP_NOT_FOUND` is `5` and `XDP_REDIRECT` is `4`.

image

image

So these two scenarios shouldn't collide.

Also, if I wrap the AF_XDP logic into a function, and call that function when an endpoint is not found, we still need to return some `xdp_action` to the `_transit` function, which leads to another action performed on the packet. I don't think this is what we want.

**Comment by w-yue** [comment]
Sorry, I miscalculated :-). Agree with what you said about function part.

**Review by w-yue — APPROVED** [review]
//LGTM

**Pull request merged**
